cube_detector:
  ros__parameters:
    minArea: 2500
    maxArea: 30000
    alpha: 0.05
    debug: false
    debug_draw_contours: false
    debug_draw_all_contours: true
    debug_draw_points: true
    debug_draw_all_points: false
    debug_draw_pose: false
