/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 10.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUV422P"
      image_width: 1280
      image_height: 720
      camera_name: "narrow_stereo"
      camera_info_url: "package://cube_detector/config/camera_info_usb2.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: 0
      auto_white_balance: false
      white_balance: 4300
      autoexposure: false
      exposure: 120
      autofocus: false
      focus: 22
