- lower:
  - 105
  - 101
  - 150
  name: blue
  upper:
  - 130
  - 255
  - 220
- lower:
  - 50
  - 60
  - 115
  name: green
  upper:
  - 80
  - 255
  - 210
- lower:
  - 0
  - 0
  - 50
  name: black
  upper:
  - 179
  - 40
  - 200
