hsv:
  blue:   [[90, 50, 70], [128,255,255]]
  red:    [[159,50,70], [180,255,255]]
  green:  [[36,50,70],  [89,255,255]]
  black:  [[0,0,0],     [180,255,30]]

cubeSize: 0.05
minArea: 2500
maxArea: 30000
alpha: 0.05
morphOpen: 3
morphClose: 5
reprojMax: 8.0
enableBlur: true
blurKernelSize: 10
displayColorMask: false
preprocessing: true
claheClip: 2.0
claheTile: 8
maskCleanup: true
drawContours: true
drawPoints: true
drawPointOrder: false
drawPose: true
shapeCheck: true
minSolidity: 0.9
minExtent: 0.7
minAspect: 0.6
maxAspect: 1.4
